server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hodduk?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: tkatnsk1


  # SMTP 설, 메일 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: hodduktest@gmail.com
    password: vojfizydvbppqfdk
    # 추가 SMTP 설정 (선택 사항)
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          starttls.required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000




  # servlet:
  #   multipart:
  #     max-file-size: 100MB
  #     max-request-size: 200MB

mybatis:
  mapper-locations: mappers/*Mapper.xml
  type-aliases-package: kr.co.hoddeokku.web.entity
  configuration:
    map-underscore-to-camel-case: true #왜 됨?

logging:
  level:
    kr.co.rland.hoddeokku.web.repository: trace #로그 출력해주는 거


