server:
  port: 8080
  servlet:
    session:
      timeout: 600
      # 초 단위
  
spring:
  datasource:
    driver-class-name: 
    url: 
    username: 
    password: 



  # SMTP 설, 메일 설정
  mail:
    host: 
    port: 
    username: 
    password: 
    # 추가 SMTP 설정 (선택 사항)
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          starttls.required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000




  # servlet:
  #   multipart:
  #     max-file-size: 100MB
  #     max-request-size: 200MB

mybatis:
  mapper-locations: mappers/*Mapper.xml
  type-aliases-package: kr.co.hoddeokku.web.entity
  configuration:
    map-underscore-to-camel-case: true #왜 됨?

logging:
  level:
    kr.co.rland.hoddeokku.web.repository: trace #로그 출력해주는 거

